//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Myproto.proto
namespace Myproto
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MsgRequest")]
    public partial class MsgRequest : global::ProtoBuf.IExtensible
    {
        public MsgRequest() { }

        private Head _head;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Head head
        {
            get { return _head; }
            set { _head = value; }
        }
        private Content _content;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Content content
        {
            get { return _content; }
            set { _content = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MsgResponse")]
    public partial class MsgResponse : global::ProtoBuf.IExtensible
    {
        public MsgResponse() { }

        private Head _head;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Head head
        {
            get { return _head; }
            set { _head = value; }
        }
        private Content _content;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Content content
        {
            get { return _content; }
            set { _content = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Head")]
    public partial class Head : global::ProtoBuf.IExtensible
    {
        public Head() { }

        private string _srcID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"srcID", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string srcID
        {
            get { return _srcID; }
            set { _srcID = value; }
        }
        private SRCType _srcType;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"srcType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public SRCType srcType
        {
            get { return _srcType; }
            set { _srcType = value; }
        }
        private readonly global::System.Collections.Generic.List<string> _dstIDs = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(4, Name = @"dstIDs", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> dstIDs
        {
            get { return _dstIDs; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Content")]
    public partial class Content : global::ProtoBuf.IExtensible
    {
        public Content() { }

        private readonly global::System.Collections.Generic.List<Msg> _msg = new global::System.Collections.Generic.List<Msg>();
        [global::ProtoBuf.ProtoMember(1, Name = @"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Msg> msg
        {
            get { return _msg; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Msg")]
    public partial class Msg : global::ProtoBuf.IExtensible
    {
        public Msg() { }

        private MsgType _type;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public MsgType type
        {
            get { return _type; }
            set { _type = value; }
        }
        private string _id = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private byte[] _body;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] body
        {
            get { return _body; }
            set { _body = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::ProtoBuf.ProtoContract(Name = @"SRCType")]
    public enum SRCType
    {

        [global::ProtoBuf.ProtoEnum(Name = @"UNITYC", Value = 1)]
        UNITYC = 1,

        [global::ProtoBuf.ProtoEnum(Name = @"APPC", Value = 2)]
        APPC = 2,

        [global::ProtoBuf.ProtoEnum(Name = @"SIM", Value = 3)]
        SIM = 3,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER", Value = 4)]
        SERVER = 4
    }

    [global::ProtoBuf.ProtoContract(Name = @"DSTType")]
    public enum DSTType
    {

        [global::ProtoBuf.ProtoEnum(Name = @"SER", Value = 1)]
        SER = 1,

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT", Value = 2)]
        CLIENT = 2,

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENTS", Value = 3)]
        CLIENTS = 3,

        [global::ProtoBuf.ProtoEnum(Name = @"CAndS", Value = 4)]
        CAndS = 4
    }

    [global::ProtoBuf.ProtoContract(Name = @"MsgType")]
    public enum MsgType
    {

        [global::ProtoBuf.ProtoEnum(Name = @"AssetLoad", Value = 1)]
        AssetLoad = 1,

        [global::ProtoBuf.ProtoEnum(Name = @"AssetUpload", Value = 2)]
        AssetUpload = 2,

        [global::ProtoBuf.ProtoEnum(Name = @"GameObjectAdd", Value = 3)]
        GameObjectAdd = 3,

        [global::ProtoBuf.ProtoEnum(Name = @"GameObjectRemove", Value = 4)]
        GameObjectRemove = 4,

        [global::ProtoBuf.ProtoEnum(Name = @"Control", Value = 5)]
        Control = 5,

        [global::ProtoBuf.ProtoEnum(Name = @"Command", Value = 6)]
        Command = 6,

        [global::ProtoBuf.ProtoEnum(Name = @"StateTransfer", Value = 7)]
        StateTransfer = 7,

        [global::ProtoBuf.ProtoEnum(Name = @"Environment", Value = 8)]
        Environment = 8
    }

}