//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: test.proto
namespace ProtocolBuffer

{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ObjectInfo")]
    public partial class ObjectInfo : global::ProtoBuf.IExtensible
    {
        public ObjectInfo() { }

        private string _object_id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"object_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string object_id
        {
            get { return _object_id; }
            set { _object_id = value; }
        }
        private Vector3 _position;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Vector3 position
        {
            get { return _position; }
            set { _position = value; }
        }
        private Vector3 _rotation;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Vector3 rotation
        {
            get { return _rotation; }
            set { _rotation = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Vector3")]
    public partial class Vector3 : global::ProtoBuf.IExtensible
    {
        public Vector3() { }

        private float _x;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float x
        {
            get { return _x; }
            set { _x = value; }
        }
        private float _y;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float y
        {
            get { return _y; }
            set { _y = value; }
        }
        private float _z;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float z
        {
            get { return _z; }
            set { _z = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}