//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CubeCE.proto
namespace CubeEvent
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CubeCE")]
	public partial class CubeCE : global::ProtoBuf.IExtensible
	{
		public CubeCE() {}
		
		private readonly global::System.Collections.Generic.List<string> _key = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(1, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> key
		{
			get { return _key; }
		}
		
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}
	
}